### ISSUE TITLE
Mis Partidas

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#15]
- **Objetivo**: obtener mis partidas y filtrar u ordenar por fecha y estado

- **Endpoint**: GET /games

- **QueryParams**: sort: List<String>,filter: List<String> (no obligatorios)

- **Respuesta correcta**: Status OK

```
[
  {
    "id": 0,
    "provinceName": String,
    "users": List<String>
    "status": "NEW"
  }
]
```

**Comment by CimimUxMaio** [comment]
@Tp-Tacs/back No me queda claro como seria la forma de los parámetros opcionales `sort` y `filter`

**Comment by CimimUxMaio** [comment]
Supongo que sort podría tener valores como: id, participants (nro de participantes), towns (nro de municipios)

Pero filter ni idea...

**Comment by dpeccia** [comment]
El enunciado dice:
> Listar todas las partidas, buscar, ordenarlas y filtrar por: fecha, estado

Por lo que para mi en el sort habría que poner _"sort=fecha"_ si queres fecha, _"sort=fecha,estado"_ si querés por ambos (dandole prioridad al primer sort. Y lo mismo para filter. En caso de que alguien ponga algo que no es eso tiraria la excepcion correspondiente

Si queres se le puede agregar un parametro mas opcional para definir si el sort queres que sea ascendente o descendente

**Comment by CimimUxMaio** [comment]
Claro, el sort lo puedo hacer "facil". El filter no me queda claro como seria un ejemplo de parámetro `filter=...`

**Comment by dpeccia** [comment]
Tenés razón, podrían ser 2 queryParams filter distintos entonces:
`filterByDate=example_date&filterByStatus=example_status`

No se, se me ocurre algo así.
Y de paso en vez de sort, sortBy queda mejor creo

**Comment by CimimUxMaio** [comment]
Claro,

Los queryParams podrian ser: sort (como definimos arriba), status=... (como filtro por un determinado estado), province=... (como filtro por provincia)

 ¿Te parece?

**Comment by dpeccia** [comment]
Me copa el de status, no entiendo para que el de provincia. El enunciado pide de fecha y estado nomas

**Comment by CimimUxMaio** [comment]
Pero es sort por fecha o filtro por fecha? Sort tiene más sentido supongo

**Comment by dpeccia** [comment]
Ambos, si haces un sort por fecha te trae todos los games ordenados por mas actual ponele.
En cambio si haces un filter por fecha pones ponele la fecha de hoy y te trae solo los games que se crearon hoy

**Comment by CimimUxMaio** [comment]
bueno dale

**Comment by PabloOve** [comment]
Acá tenés que filtrar los de una fecha específica o en un rango de fechas? Yo hice un filtrar por rango de fechas para el admin. 
Mañana me pongo a leer bien todos los otros issues!
