### ISSUE TITLE
Obtener Partida

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#18]
- **Objetivo**: obtener una partida en específico

- **Endpoint**: GET /games/{id}

- **QueryParams**: N/A

- **Respuesta correcta**: Game entero

**Comment by CimimUxMaio** [comment]
@Tp-Tacs/back Aca debería simplemente devolver el game con dicho id? O debería chequear que el usuario logueado este participando de ese game?

**Comment by dpeccia** [comment]
Tecnicamente se podría devolver el game con dicho id porque desde el front para conocer los ids deberian haber hecho un GET games antes. Pero para mí hay que chequear (como todo) tanto desde el front como desde el back que el usuario que te mandó el request pertenezca al game

**Comment by CimimUxMaio** [comment]
@dpeccia entonces solo puedo traer games propios?

**Comment by dpeccia** [comment]
Yes, este endpoint esta pensado para obtener solamente el game si perteneces a él
