### ISSUE TITLE
Modificar Estado de una Partida (Rendirse?)

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#19]
- **Objetivo**: modificar estado de una partida (seguramente solo cancelarlo)

- **Endpoint**: PUT /games/{id}

- **QueryParams**: N/A

- **Params**: el id del game

Este endpoint sería equivalente a un surrender, que puede o no modificar el estado de la partida a cancelada (dependiendo de la cantidad de jugadores de la partida)

**Comment by CimimUxMaio** [comment]
@PabloOve fijate que ahora Game tiene todo lo que necesitas para poder hacer lo que estas haciendo en este request sin necesidad de que te manden un form en el body. Simplemente con el id del game ya podrías obtener todos los datos.
