### ISSUE TITLE
Atacar Municipio

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#20]
- **Objetivo**: poder atacar un municipio

- **Endpoint**: POST /games/{id}/actions/attack

- **Params**: id de la partida

- **Body**:
```
{
    from: Int,
    to: Int
}
```

**Comment by dpeccia** [comment]
@Tp-Tacs/back tengo dudas con esta parte del enunciado:

![image](https://user-images.githubusercontent.com/42644816/93030308-5f6e9a80-f5f8-11ea-9bbf-bfc21bc8b039.png)

Suponiendo los siguientes casos:

1. Después del ataque: municipio **atacante** (user1) queda con **4 gauchos**, municipio **defensor** (user2) queda con **3 gauchos**. Todo sigue igual? O user1 se queda con ambos por ser 4>3 ?
2. Después del ataque: municipio **atacante** (user1) queda con **4 gauchos**, municipio **defensor** (user2) queda con **4 gauchos**. Todo sigue igual?
3. Después del ataque: municipio **atacante** (user1) queda con **4 gauchos**, municipio **defensor** (user2) queda con **0 gauchos**. User1 se quedaría con ambos?
4. Después del ataque: municipio **atacante** (user1) queda con **0 gauchos**, municipio **defensor** (user2) queda con **1 gaucho**. User2 se quedaría con ambos? O municipio atacante sigue siendo del user1

**Comment by CimimUxMaio** [comment]
Yo creo que con cada ataque se reducen los gauchos de c/u pero el atacante solo obtiene el municipio cuando el defensor queda en 0

**Comment by CimimUxMaio** [comment]
si el atacante queda en 0 no pasa nada pero en el turno del defensor puede atacar a ese municipio y ganarlo ya que ahora, estando defendiendo, el municipio tiene 0 gauchos

**Comment by dpeccia** [comment]
dale, me parece bien tomarlo asi entonces

**Comment by Pato94** [comment]
Es verdad que esta ~mal redactado~ un poco ambiguo, lo paso al grupo de docentes. Dicho eso, la decision que tomaron me parece super piola, vayan con eso!
