### ISSUE TITLE
Estadísticas de un Municipio

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#22]
- **Objetivo**: obtener estadísticas de produccion y defensa de un municipio junto con la imagen asociada

- **Endpoint**: GET /games/{id}/towns/{idTown}

- **Params**: id de la partida, idTown del municipio

- **Respuesta correcta**: 
```
{
    // TODO ver que mandarle
}
```

**Comment by dpeccia** [comment]
@PabloOve puede ser que te hayas dejado esto en otro branch? No lo veo en master

**Comment by PabloOve** [comment]
@dpeccia @CimimUxMaio Me iba a poner con esto y justo que Diego lo mencionó, les pregunto. Que piensan que tendríamos que mostrar en cuanto a producción y defensa? Estoy leyendo bien toda la lógica y de lo que veo, esto serviría para el calculo de cuantos gauchos habría que sumar. También está el multiplicador de ataque o defensa.. Pero qué podría mostrarse ahí? O se les ocurre alguna otra cosa estadística que pueda aparecer dependiendo de como se vaya dando la partida?

**Comment by dpeccia** [comment]
@PabloOve por ahora lo unico que se me ocurre ya que el enunciado dice 

> estadísticas de producción y defensa de cada municipio

es que se muestre cuantos gauchos se generaron en modo producción y cuantos en modo defensa.
También se podría mostrar un histórico de acciones realizadas en el municipio, pero entiendo que no sería lo que estan pidiendo.
@CimimUxMaio vos que opinas?

**Comment by PabloOve** [comment]
Lo de cuantos se generaron en modo producción y defensa estoy de acuerdo. Las especializaciones se encargan de generar gauchos así que cuantos generó cada una debería ser la estadística que más interesa mostrar. Después de esa no se me ocurre otra pero voy arrancando con esa

**Comment by CimimUxMaio** [comment]
Yo creo que lo importante es eso, los gauchos que genera. Debería haber un método que diga gauchosAGenerar() o algo asi (si todavía no hay) y sacas los números de ahi. No le daría mucha vuelta. Sumale el nombre del municipio la url de la imagen, cantidad de gauchos que tiene actualmente, altura; todo lo que necesite front para mostrar al municipio.
