### ISSUE TITLE
Modificar Especialización de un Municipio

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#23]
- **Objetivo**: poder cambiar la especialización de un municipio entre Producción y Defensa

- **Endpoint**: PUT /games/{id}/towns/{idTown}

- **Params**: id de la partida y id del municipio

- **Body**:
```
{
    specialization: String
}
```

**Comment by dpeccia** [comment]
@Tp-Tacs/back respecto a esto:

![image](https://user-images.githubusercontent.com/42644816/93029770-0f8dd480-f5f4-11ea-8073-c3e4f3b338f5.png)

Se refiere a que genera esa cantidad de gauchos en cada turno? osea que cada turno se suman esos? o simplemente si el municipio esta en modo proudccion siempre tiene esa cantidad de gauchos?

**Comment by CimimUxMaio** [comment]
Supongo que sera algo como: specialization.gauchosToGenerate() = esa formula

**Comment by dpeccia** [comment]
sisi eso si, lo que no entiendo es si cada turno se le suma specialization.gauchosToGenerate() a la cantidad de gauchos que tenés o si directamente la cantidad de gauchos que tenes es igual a specialization.gauchosToGenerate() siempre

**Comment by Pato94** [comment]
No, los gauchos se producen en cada turno, de otra forma el municipio con mas gauchos es inconquistable, y la función de mover gauchos no tendría sentido.
Esa formula indica cuántos gauchos son producidos (agregados al total) en cada turno.
