### ISSUE TITLE
Servicios externos

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#24]
Consulta de servicios externos: GeoRef, datos topológicos, Pixabay

**Comment by dpeccia** [comment]
@CimimUxMaio revivo este comentario que había dejado sobre el testeo de los servicios externos en un pull request, por los comentarios que nos hizo Pato por mail sobre la entrega 2:

> Juan, vos que estas con los servicios externos, una gran manera de testearlos es hacer por un lado un test de integración que le pegue posta a la API externa, y te fijes si los datos que devuelve son los que queres y demás. Es mas para nosotros para si se rompe todo cuando estas usando la app, corriendo ese test sepamos que no hay nignun error de ese lado.
> Por otro lado, después si tenes que testear un controller haces lo que voy a decir abajo:

La idea sería entonces que hayan test de integración (sin mocks, testeando que recibimos lo que queremos) y unit tests (con mocks, suponiendo que ya tenemos el json respuesta testeariamos como se parsean esos datos y donde quedan) en los servicios

**Comment by dpeccia** [comment]
@CimimUxMaio un bug que encontré acá es que cuando TopoData tira TimeOut la excepción no está manejada y terminamos devolviendole a front un 500

**Comment by CimimUxMaio** [comment]
@dpeccia Como reproduzco esto? No sabría cómo manejarlo, no se donde se tira.

**Comment by dpeccia** [comment]
@CimimUxMaio es especificamente en el llamado a topodata. En cuanto a como reproducirlo, yo varias veces intenté crear un Game con CABA y me tiró eso. Cualquier cosa avisame

**Comment by CimimUxMaio** [comment]
pusiste "CABA" o "Ciudad autonoma de buanos aires"?
