### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by CimimUxMaio** [Tp-Tacs/TP-TACS#27]
@Tp-Tacs/back 

Re colgamos pero los tokens se crean a partir del mail del usuario que se loguea, deberiamos cambiarlo para que el subject del token sea el id del usuario.

@PabloOve Fijate que en "PUT /games/{id}" (aka surrender) estas usando le token para obtener datos del usuario a partir de su mail. Cuando se modifique esto a id, vas a tener que replantear la solucion. Pero creo que va a quedar mucho mejor.

**Comment by dpeccia** [comment]
Es verdad, hay que cambiarlo a que se obtenga del id
