### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#28]
Falta agregar:

- Badge que diga Tests -> Passed
- Badge con el porcentaje de cobertura de tests

Comentarios generales:

- Ojo que en master quedó un Build->Failing (cosa que no debería pasar)
- En master no corren todos los tests (cosa que tampoco debería pasar)

**Comment by CimimUxMaio** [comment]
@dpeccia Los tests que fallan son los de integration que, no se por qué, a veces fallan y a veces no.

¿A que te referis con que en master no corren todos los tests?

**Comment by dpeccia** [comment]
Me referia a eso, lo reviso, no hay drama

**Comment by dpeccia** [comment]
Reabro ya que nos falta que funcione bien el badge de test coverage
