### ISSUE TITLE
Cambio en las excepciones

### ISSUE THREAD

**Issue by CimimUxMaio** [Tp-Tacs/TP-TACS#29]
@Tp-Tacs/back 

Cambie la forma en que se modelaban las excepciones. Creo que asi es mas facil de encontrar y de entender el proposito de cada excepcion que creemos.

Las CustomExceptions se dividen en 5 categorias, asimismo cada una de las categorias simboliza un codigo de estado http. Cada categoria es tambien una sealed class (es abstracta), dentro de la misma se encuentran las excepciones mas especificas.

1. NotFound
2. BadRequest
3. Forbidden
4. Unauthorized
5. Service: Para los errores en las requests a servicios externos, este no supe que httpstatus asignarle, le deje el status FAILED_DEPENDENCY que me parecio el mas apropiado pero ni idea.

Para mapear a cada excepcion con un statusHttp cree una classe: `BaseController` de la cual heredan todos los controllers. Esta tiene el metodo `checkAndGetToken(authCookie)` para no repetir siempre lo mismo, y, además, define todos los handlers, uno para cada una de los codigos http que se mapean con las excepciones.

Despues fijense si mergee correctamente las excepciones que crearon uds, porque tuve que adaptarlas a este modelo y puede que le haya pifiado a alguna.

**Comment by dpeccia** [comment]
Perfecto! Me parece bien dejarlo asi

**Comment by CimimUxMaio** [comment]
@Tp-Tacs/back 

Si les parece cuando tenga un poco de tiempo, voy a cambiar todo lo que retorne un `Option` por un `Either`. Haciendo lo mencionado arriba me di cuenta que estamos instanciando/tirando excepciones especificas por todos lados y esto podria probocar una equivocacion con el tipo de excepcion. Con either solo habria que hacer ``.getOrElse { throw it }` y nos abstraeriamos del tipo concreto de la excepcion.

Un ejemplo serian los repos:

Si por ejemplo busco un User por id y no esta, esta claro que la excepcion que deberia tirar siempre es `CustomException.NotFound.UserNotFoundException`. Los mismo para los Games. Hacer que `Repository.getById`, por ejemplo, retorne un Either, evitaria que en muchas partes del codigo hagamos la misma logica de: `.getOrElse { throw CustomException.NotFound.UserNotFoundException() }`
