### ISSUE TITLE
Turno

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#30]

**Comment by dpeccia** [comment]
![image](https://user-images.githubusercontent.com/42644816/93119069-8e881900-f697-11ea-9cf1-1e0af38d62e7.png)

**Comment by dpeccia** [comment]
@Tp-Tacs/back deberíamos entonces agregar un endpoint para que desde el front el usuario indique que finalizó el turno.
Les parece `PUT /games/{id}/actions/turn` o `PUT /games/{id}/actions/` directamente?

**Comment by CimimUxMaio** [comment]
Claro. `PUT /games/{id}/actions/` me parece bien
