### ISSUE TITLE
Servicios, servicios everywhere

### ISSUE THREAD

**Issue by CimimUxMaio** [Tp-Tacs/TP-TACS#31]
@Tp-Tacs/back 

No me queda claro como es la idea de los servicios del estilo: `GamesService`, `UsersService`, etc.

¿Cuál es su objetivo? ¿Qué ventajas tienen?

Me mareé un poco ajajaja

**Comment by dpeccia** [comment]
Te doy el ejemplo con #14 :

- UserController -> método getUsers : queda con la responsabilidad de ser la puerta de entrada de la API, recibir los parámetros (queryParams, pathParams, bodyParams) y convertirlos a un tipo de dato del dominio, validar que el usuario esté logueado o tirar excepción

- UsersService -> método getUsers : tiene la lógica de este endpoint. ¿Qué tiene que hacer? Si no se pasa un usuario particular devolver los datos de todos los usuarios que no sean admin, sino verificar que el usuario exista y devolverlo o tirar la excepción correspondiente

De esta manera para testear este método del controller, lo único necesario a testear queda en el Service, donde está la lógica.
Como el Controller no tiene lógica, no tiene ningún punto de fallo que sea necesario testear, más que la validación del JWT y que status codes devuelve, que se testea ya en el Integration Test.

Por ahora solo apliqué esta lógica del Service en ese metodo y en el del login, me faltaría en los demás

**Comment by CimimUxMaio** [comment]
Ahhhhhhh buenisimo.

Entonces por ahi `GameControllerService`, `UserControllerService`, serian nombres más claros.

Por otro lado, hay logica que sigue estando dentro de los controllers para algunos endpoints. Habria que pasarla al service correspondiente, no?

**Comment by dpeccia** [comment]
> Entonces por ahi `GameControllerService`, `UserControllerService`, serian nombres más claros.

Sí, me parece bien cambiarles el nombre

> Por otro lado, hay logica que sigue estando dentro de los controllers para algunos endpoints. Habria que pasarla al service correspondiente, no?

Sip, cambie cada uno el que corresponde a los issues que tiene asignados, asi no nos hacemos quilombo

**Comment by CimimUxMaio** [comment]
Dale perfecto. Lo tengo en cuenta.
