### ISSUE TITLE
Duda Pixabay

### ISSUE THREAD

**Issue by CimimUxMaio** [Tp-Tacs/TP-TACS#32]
@Tp-Tacs/back

Entiendo que tanto los municipios y las provincias tienen que tener asociada una imagen. ¿Pero cómo seleccionamos esta imagen?¿Le pegamos a Pixabay con el nombre de alguno de estos y usamos la primera imagen que retorne de las tantas? Esto último no tendría sentido porque la imagen puede ser cualquier cosa, no estaríamos seguros de si la imagen que estamos obteniendo nos es de utilidad; además, esta imagen podría cambiar en cualquier momento.

¿Entonces? Propusimos tener en algún archivo los ids (de pixabay) de las imágenes que queremos asociar a cada provincia. Pero:

1) En el caso de los municipios esto sería imposible y no tendría sentido ya que cada provincia tiene muchísimos municipios y contemplarlos todos seria un quilombo.

2) Si estamos guardando en un archivo una lista de ID correspondiente a la imagen de cada provincia. Aunque no solucione el problema del punto 1, creo que es muchisimo mas conveniente en vez de guardar el ID de la imagen guardar directamente el URL. Esto es lo mismo pero evitaria hacer la request a la API.

Para solucionar el problema 1 planteado, se me ocurre que en el caso de los municipios SI se utilice una imagen "random" (la primera respuesta de pixabay), mientras que para las provincias que son muchas menos si se defina en un archivo el URL de la imagen seleccionada para cada una.
 - De esta forma, se evitaría el uso innecesario de la API para buscar las imágenes de las provincias, y además se podrían definir las imágenes que nos gusten realmente para que representen a cada una de ellas.
 - Por otro lado, la API se seguiría utilizando (entiendo que es obligatorio su uso) para obtener las imágenes de los municipios. En este caso las imágenes no nos importa seleccionarlas cuidadosamente, ya que solo las necesitamos como representación del municipio cuando el usuario pase el mouse por encima de alguna para ver su información.

**Comment by dpeccia** [comment]
> 1. En el caso de los municipios esto sería imposible y no tendría sentido ya que cada provincia tiene muchísimos municipios y contemplarlos todos seria un quilombo.

Estoy de acuerdo en que es inviable para los municipios

> 2. Si estamos guardando en un archivo una lista de ID correspondiente a la imagen de cada provincia. Aunque no solucione el problema del punto 1, creo que es muchisimo mas conveniente en vez de guardar el ID de la imagen guardar directamente el URL. Esto es lo mismo pero evitaria hacer la request a la API.

Me parece perfecto lo de guardar las urls para las provincias

> De esta forma, se evitaría el uso innecesario de la API para buscar las imágenes de las provincias, y además se podrían definir las imágenes que nos gusten realmente para que representen a cada una de ellas.

> Por otro lado, la API se seguiría utilizando (entiendo que es obligatorio su uso) para obtener las imágenes de los municipios. En este caso las imágenes no nos importa seleccionarlas cuidadosamente, ya que solo las necesitamos como representación del municipio cuando el usuario pase el mouse por encima de alguna para ver su información.

Me parece bien la decision de tener una imagen random por municipio
+10 a todo, preguntemosle a Pato que le parece

**Comment by dpeccia** [comment]
@Pato94 te parece bien lo que definimos con @CimimUxMaio sobre como usariamos Pixabay en el tp ?

**Comment by Pato94** [comment]
Me parece bien, puede ser que la api de pixabay soporte "tags" para agregar en la busqueda de imagenes de un municipio? Si es así, quizás pueden filtrar con un tag que sea "building", para reducir un poco el riesgo de tomar imagenes random random. Si no fuese así, tengo mala data, y su solución me parece bien.

**Comment by dpeccia** [comment]
Es correcto @Pato94 , la api de pixabay soporta filtros/tags. Los agregamos para que no sea tan random entonces!
