### ISSUE TITLE
Persistencia

### ISSUE THREAD

**Issue by dpeccia** [Tp-Tacs/TP-TACS#40]
![image](https://user-images.githubusercontent.com/42644816/94872451-02118080-0423-11eb-9c20-6ece12c90a41.png)

@Tp-Tacs/back deberíamos definir db no? Yo solamente trabajé con relacionales (MySQL y SQLserver)

**Comment by dpeccia** [comment]
Podriamos ir con Mongo sino no?

**Comment by CimimUxMaio** [comment]
Como quieran, no tengo ninguna preferencia. Nunca usé mongo ni use una relacional mas que para el tp de diseño.

**Comment by dpeccia** [comment]
Oka, ahí hice un branch mongoDB para ir probando que tal es, por ahora funciona el login, sign up y log out y esta bueno.
Hay mil cosas por mejorar y estan rotos los tests, ahora veo de fixear eso
